/**
 * Error codes used in ValidationResult.errors[].code.
 * These are the canonical codes — add new ones sparingly.
 */
export const ERROR_CODES = {
  // Graph structure
  CYCLE_DETECTED: 'CYCLE_DETECTED',
  ORPHAN_NODE: 'ORPHAN_NODE',
  MISSING_INPUT_PORT: 'MISSING_INPUT_PORT',
  UNCONNECTED_REQUIRED_INPUT: 'UNCONNECTED_REQUIRED_INPUT',
  TYPE_MISMATCH: 'TYPE_MISMATCH',
  UNKNOWN_NODE_TYPE: 'UNKNOWN_NODE_TYPE',
  NO_OUTPUT_NODE: 'NO_OUTPUT_NODE',
  UNREACHABLE_OUTPUT: 'UNREACHABLE_OUTPUT',
  MULTIPLE_OUTPUT_NODES: 'MULTIPLE_OUTPUT_NODES',
  DUPLICATE_PORT_CONNECTION: 'DUPLICATE_PORT_CONNECTION',
  SELF_REFERENCE: 'SELF_REFERENCE',

  // Formula
  FORMULA_INVALID_AST: 'FORMULA_INVALID_AST',
  FORMULA_UNKNOWN_VARIABLE: 'FORMULA_UNKNOWN_VARIABLE',
  FORMULA_UNKNOWN_OPERATOR: 'FORMULA_UNKNOWN_OPERATOR',
  FORMULA_INVALID_CONFIG: 'FORMULA_INVALID_CONFIG',

  // Plugin
  PLUGIN_CONFIG_VALIDATION_FAILED: 'PLUGIN_CONFIG_VALIDATION_FAILED',
  PLUGIN_EXECUTION_ERROR: 'PLUGIN_EXECUTION_ERROR',
  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',

  // Execution
  EXECUTION_NODE_FAILED: 'EXECUTION_NODE_FAILED',
  EXECUTION_ABORTED: 'EXECUTION_ABORTED',
  VERSION_NOT_PUBLISHED: 'VERSION_NOT_PUBLISHED',
  VERSION_IMMUTABLE: 'VERSION_IMMUTABLE',

  // General
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
